require 'cancanright/model/right'
require 'cancanright/model/role'
require 'cancanright/ability'
require 'cancanright/controller_additions'
require 'cancanright/error'
require 'cancanright/role_model'
require 'cancanright/rule'
